config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put "like", to:    "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end
  
  root 'posts#main'

  

end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  resourcify
  belongs_to :user
  
  #조회수 기능
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:main]
  before_action :hash_tag
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    
  end
  
  def main
    authorize! :main, @post
  end
  

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

# 공감
def upvote
    @post = Post.find(params[:id])
  if ((current_user.voted_up_on? @post) == true)
        @post.unliked_by current_user
        redirect_to(request.referrer, :notice => '공감취소했습니다')
    else
        @post.upvote_by current_user
        redirect_to(request.referrer, :notice => '공감했습니다')
  end
end

# 비공감
def downvote
    @post = Post.find(params[:id])
    if ((current_user.voted_down_on? @post) == true)
        @post.unliked_by current_user    
        redirect_to(request.referrer, :notice => '비공감취소했습니다')
    else
        @post.downvote_from current_user
        redirect_to(request.referrer, :notice => '비공감했습니다')
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
    
    # def check_page
      
    # end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :hashtag, :user_id)
    end
    
    
    # 해시태그 랜덤 뽑기
    def hash_tag
      
      @hash_1 = Array.new # 배열을 하나 새로 만든다.
      hash = Post.all.order("RANDOM()").first(1) # 최신 포스트를 모두 가져온 다음
      hash.each do |h| # each로 하나씩 x로
        @hash_1.push(h) # notice_1에서 x를 push하면
        break;
      end  
    end  
    



    
    
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_category.html.erb
<h2>공감</h2>
<% @posts.each do |post| %>
  <div class="card">
    <a href="/posts/<%= post.id %>">
      <p><%= post.created_at.strftime("%Y년%m월%d일, %H시%M분") %></p>
      <h3>"<%= post.title %>"</h3>
      <h4> 공감 <%= post.get_upvotes.size%> | ㅈㄹ <%= post.get_downvotes.size %></h4>
    </a>
  </div>
<% end %>   

app/views/posts/_footer.html.erb
<footer class="py-5 footer">
    <div class='footer'>
      <p class="m-0 text-center">&copy; 2018 LIKELION SAHMYOOKUNIVERSITY </p>
    </div>
</footer>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  
  <div class="form-group">
    <%= f.label :제목 %>
    <%= f.text_field :title, required: true, class:"form-control title", id:"exampleFormControlTextarea1", rows:"3", maxlength: "20" %>
  </div>
  
  <div class="field">
    <%= f.text_field :hashtag, class:"form-control title", maxlength: "10", placeholder: "#" %>
  </div>
  
  <!--tinymce 잼-->
  <div class="form-group">
    <%= tinymce %>
    <%= f.label :내용, class: "label2" %>
    <%= f.text_area :content, :rows => 20, class: "form-control tinymce", maxlength: "20" %>
  </div>
  
  <div class="new_btn_con_con">
    <div class="new_btn_con">
      <div class="new_btn">
       <%= f.submit value="작성", class:'btnlogin btnlogin-primary new' %>
      </div>
      <div class="new_btn">
       <%= button_to '취소', posts_path, class: "btnlogin btnlogin-primary new" %>
      </div>
    </div>
  </div>

<% end %>

app/views/posts/_hashtag.html.erb
<% @hash_1.each do |hash| %>
  <%= hash.hashtag %>
<% end %>

app/views/posts/_logo.html.erb
<a href="/posts"><img src='/assets/hand' class="logo"></img></a>

app/views/posts/_side.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
  <ul class="nav sidebar-nav">
    <li class="sidebar-brand">
      <h1><%= current_user.nickname %></h1>
      <p><%= link_to '내 정보', edit_user_registration_path %> | <%= link_to '나가기', destroy_user_session_path, method: 'delete' %></p>
    </li>
    
    <li>
        <a><%= link_to '글쓰기', new_post_path %></a>
    </li>
    <li>
        <a href="#">최다공감</a>
    </li>
    <li>
        <a href="#">랜덤불만</a>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
      <!--<ul class="dropdown-menu" role="menu">-->
      <!--  <li class="dropdown-header">Dropdown heading</li>-->
      <!--  <li><a href="#">Action</a></li>-->
      <!--  <li><a href="#">Another action</a></li>-->
      <!--  <li><a href="#">Something else here</a></li>-->
      <!--  <li><a href="#">Separated link</a></li>-->
      <!--  <li><a href="#">One more separated link</a></li>-->
      <!--</ul>-->
  </ul>
</nav>

<script>
$(document).ready(function () {
  var trigger = $('.hamburger'),
      overlay = $('.overlay'),
     isClosed = false;

    trigger.click(function () {
      hamburger_cross();      
    });

    function hamburger_cross() {

      if (isClosed == true) {          
        overlay.hide();
        trigger.removeClass('is-open');
        trigger.addClass('is-closed');
        isClosed = false;
      } else {   
        overlay.show();
        trigger.removeClass('is-closed');
        trigger.addClass('is-open');
        isClosed = true;
      }
  }
  
  $('[data-toggle="offcanvas"]').click(function () {
        $('#wrapper').toggleClass('toggled');
  });  
});
</script>

app/views/posts/_sidebtn.html.erb
<button type="button" class="hamburger is-closed" data-toggle="offcanvas">
  <span class="hamb-top"></span>
	<span class="hamb-middle"></span>
  <span class="hamb-bottom"></span>
</button>

app/views/posts/_time.html.erb
<div class="timezone">
<p class="align-middle"><%= Time.zone.now.strftime("%Y년%m월%d일, %H시%M분") %></p>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="title-custom">수정하기</h1>
  <hr>
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div id="wrapper">
  
  <!-- Sidebar -->
  <%= render 'side' %>
    
  <!-- Page Content -->
  <div id="page-content-wrapper">
    <%= render 'time' %>
    <%= render 'sidebtn' %>
    <div class="container">
      <div class="row">
          <div class="col-md-8 index">
            <div class="topicbox align-middle">
              <h1>"오늘의 불만"</h1>
              <p>#<%= render 'hashtag' %></p>
            </div>
                <%= link_to(image_tag('/assets/add-button'), new_post_path, class: "addicon")%>
          </div>
          <div class="col-md-4 index" >
              <%= render 'category' %>
          </div>
        </div>
      </div>
      <%= render 'footer' %>
  </div>
</div>
  <!-- /#page-content-wrapper -->
<!-- /#wrapper -->

<!--<td><%#= post.title %></td>-->
<!--<td><%#= post.content %></td>-->
<!--<td><%#= link_to 'Show', post %></td>-->
<!--<td><%#= link_to 'Edit', edit_post_path(post) %></td>-->
<!--<td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->

app/views/posts/main.html.erb
<!-- Page Content -->
<div class="container main">
      <%= render '/posts/logo' %>
      <div class="mainmentbox">
        <div class="mainment" style="writing-mode: tb-rl;">
          <div class="mainment1">
            <span class="ment">불</span><span>만</span></br>
          </div>
          <div class="mainment2">
            <span class="ment">모</span><span>든</span></br>
          </div>
          <div class="mainment3">
            <span class="ment">세</span><span>상의</span>
          </div>
        </div>
      </div>
      <div class="mainlogin">      
      <% if user_signed_in? %>
      <!-- 혹시 몰라서 로그아웃을 만들어 놓음  -->
        <%= button_to '로그아웃', destroy_user_session_path, method: 'delete', class: "btnmain" %>
      <% else %>
        <p><%= button_to '로그인', new_user_session_path, class: "btnmain" %></p>

        <p><%= link_to '회원가입', new_user_registration_path, class: "btnmain_sign_in" %></p>
        

      </div>
      <% end %>
      <!-- Page Footer -->
      <%= render 'footer' %>
</div>




<!--<script src="vendor/jquery/jquery.min.js"></script>-->
<!--<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>-->

app/views/posts/new.html.erb
<div class="container">
  <h1 class="title-custom"># 불만</h1>
  <hr>
  <%= render 'form', post: @post %>
</div>
  <%= render 'footer' %>

app/views/posts/show.html.erb
<div id="wrapper">
  
  <!-- Sidebar -->
  <%= render 'side' %>
    
  <!-- Page Content -->
  <div id="page-content-wrapper">
    <%= render 'time' %>
    <%= render 'sidebtn' %>
    <div class="container">
      <div class="row">
          <div class="col-md-8 index">
            <div class="topicbox align-middle">
              <h1>"<%= @post.title %>"</h1>
              <p><%= @post.content.html_safe %></p>
              <p>#<%= @post.hashtag %></p>
              
              <%= link_to "공감", like_post_path(@post), method: :put %> <%= @post.get_upvotes.size%> |
              <%= link_to "ㅈㄹ", dislike_post_path(@post), method: :put %> <%= @post.get_downvotes.size %>
              <br><br>
              <% if user_signed_in? %>
              <% if @post.user == current_user %>
                <%= link_to '수정', edit_post_path(@post) %> |
                <%= link_to '삭제', @post, method: :delete, data: { confirm: '게시글을 삭제하시겠습니까?' } %> |
              <% elsif current_user.has_role? 'admin'%>
                <%= link_to '수정', edit_post_path(@post) %> |
                <%= link_to '삭제', @post, method: :delete, data: { confirm: '게시글을 삭제하시겠습니까?' } %> | 
              <% end %>
                <%= link_to '뒤로가기', posts_path %>
              <% else %>
                <%= link_to '뒤로가기', posts_path %>
              <% end %> 
            </div>
          </div>
          <div class="col-md-4 index">
              <%= render 'category' %>
          </div>  
        </div>
    </div>
    <!-- Page Footer -->
    <%= render 'footer' %>
  </div>
</div>